INSERT INTO Person VALUES (1,'Programmer','F ','Greenville', NULL)
INSERT INTO Person VALUES (2,'Student','M ', 'Clemson', 21)
INSERT INTO Person VALUES (3,'Baker', 'M ', 'Mars', 55)
INSERT INTO Person VALUES (4,'Author','F ','Greensboro', 35)
INSERT INTO Person VALUES (5, 'Surfer','M ','Seneca', 18)
INSERT INTO Person VALUES (6, 'Salesman', 'F ', 'Pickens', 78)
INSERT INTO Person VALUES (7, 'Retired', 'F ','Greenville', 98)
INSERT INTO Person VALUES (8, 'Student', 'M ', 'Seneca', 23)
INSERT INTO Person VALUES (9, 'Builder', 'F ', 'Charleston', 36)
INSERT INTO Person VALUES (10, 'Chef', 'M ', 'Greenville', NULL)
